package Sistema;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diaz
 */
public class vPaciente extends javax.swing.JFrame {
DefaultTableModel ModeloTabla;
    private String[] registro;
    private String SSQL;
    private Object tablacontactos;
    private Object tabla;
    ResultSet rs; 
    public vPaciente() {
        initComponents();
        setTitle("Paciente");
        setResizable(false);
        this.setLocation(400,100);
        bloquear();
        setIconImage(new ImageIcon(getClass().getResource("../Sistema/iconoSis.png")).getImage());
        lares.setVisible(false);
        fecha1.setVisible(false);
    }
void limpiar(){
    tfFolioP.setText(null);
    tfNombreP.setText(null);
    tfApellidoPatP.setText(null);
    tfApellidoMatP.setText(null);
    FKdTablaPaciente.setText(null);
}
void bloquear(){
    tfFolioP.setEnabled(false);
    tfNombreP.setEnabled(false);
    tfApellidoPatP.setEnabled(false);
    tfApellidoMatP.setEnabled(false);
    FKdTablaPaciente.setEnabled(false);
    btntutor.setEnabled(false);
    FechaP.setEnabled(false);
    btnGuardarP.setEnabled(false);
    btnBorrarP.setEnabled(false);
    btnEditarP.setEnabled(false);
    btnBuscarP.setEnabled(false);
}
void desbloquear(){
    tfFolioP.setEnabled(true);
    tfNombreP.setEnabled(true);
    tfApellidoPatP.setEnabled(true);
    tfApellidoMatP.setEnabled(true);
    FKdTablaPaciente.setEnabled(true);
    btntutor.setEnabled(true);
    FechaP.setEnabled(true);
    btnGuardarP.setEnabled(true);
    btnBorrarP.setEnabled(true);
    btnEditarP.setEnabled(true);
    btnBuscarP.setEnabled(true);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btntutor = new javax.swing.JButton();
        FechaP = new com.toedter.calendar.JDateChooser();
        tfNombreP = new javax.swing.JTextField();
        tfApellidoPatP = new javax.swing.JTextField();
        tfApellidoMatP = new javax.swing.JTextField();
        femenino = new javax.swing.JRadioButton();
        masculino = new javax.swing.JRadioButton();
        FKdTablaPaciente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tfFolioP = new javax.swing.JTextField();
        fecha1 = new javax.swing.JLabel();
        lares = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        NuevoP = new javax.swing.JButton();
        btnGuardarP = new javax.swing.JButton();
        btnEditarP = new javax.swing.JButton();
        btnBorrarP = new javax.swing.JButton();
        btnBuscarP = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paciente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 36))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Apellido Paterno");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Apellido Materno");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Fecha de nacimiento");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Sexo");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Ingresar la clave de su tutor");

        btntutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/Busca1.png"))); // NOI18N
        btntutor.setText("Buscar");
        btntutor.setContentAreaFilled(false);
        btntutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntutorActionPerformed(evt);
            }
        });

        FechaP.setDateFormatString("yyyy/MM/d");

        tfNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombrePActionPerformed(evt);
            }
        });

        tfApellidoPatP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoPatPActionPerformed(evt);
            }
        });

        tfApellidoMatP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoMatPActionPerformed(evt);
            }
        });

        buttonGroup1.add(femenino);
        femenino.setText("F");

        buttonGroup1.add(masculino);
        masculino.setText("M");

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave_t", "Nombre", "Apellido Paterno", "Apellido Materno"
            }
        ));
        jScrollPane2.setViewportView(tbDatos);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Folio");

        tfFolioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFolioPActionPerformed(evt);
            }
        });

        fecha1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lares.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7)
                        .addGap(136, 136, 136)
                        .addComponent(tfFolioP, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(FKdTablaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btntutor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addComponent(femenino)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(masculino)
                                .addGap(31, 31, 31)
                                .addComponent(lares, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(118, 118, 118)
                                .addComponent(tfNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(59, 59, 59))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(35, 35, 35)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfApellidoPatP, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfApellidoMatP, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FechaP, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfFolioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfApellidoPatP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfApellidoMatP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(FechaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(femenino)
                    .addComponent(masculino)
                    .addComponent(lares, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(FKdTablaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btntutor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 574));

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);

        NuevoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/Guar2.png"))); // NOI18N
        NuevoP.setContentAreaFilled(false);
        NuevoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoPActionPerformed(evt);
            }
        });

        btnGuardarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/iGuardar.png"))); // NOI18N
        btnGuardarP.setContentAreaFilled(false);
        btnGuardarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPActionPerformed(evt);
            }
        });

        btnEditarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/iEditar.png"))); // NOI18N
        btnEditarP.setContentAreaFilled(false);
        btnEditarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPActionPerformed(evt);
            }
        });

        btnBorrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/borrar.png"))); // NOI18N
        btnBorrarP.setContentAreaFilled(false);
        btnBorrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarPActionPerformed(evt);
            }
        });

        btnBuscarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/Busca1.png"))); // NOI18N
        btnBuscarP.setContentAreaFilled(false);
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrarP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnEditarP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(NuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrarP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/iVolver.png"))); // NOI18N
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 23, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        vInicio abrir = new vInicio();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPActionPerformed
        conexion cc=new conexion();
        Connection cn = cc.conexion();
        String nom,foli,sex = null,apat,amat,cl;
        String sql="";
        if(femenino.isSelected()){
            sex="F";
        } else if (masculino.isSelected())
            sex="M";
        foli = tfFolioP.getText();
        nom = tfNombreP.getText();
        apat = tfApellidoPatP.getText();
        amat = tfApellidoMatP.getText();
        cl = FKdTablaPaciente.getText();
        if (tfFolioP.getText().length()==0 || tfNombreP.getText().length()==0 || tfApellidoPatP.getText().length()==0 || tfApellidoMatP.getText().length()==0 || FKdTablaPaciente.getText().length()==0){
            JOptionPane.showMessageDialog(null,"ERROR CAMPOS VACIOS");
        }
        else{
        sql="INSERT INTO paciente (folio_p,nombre,apellidoPat,apellidoMat,fecha_nac,sexo,clave_t) VALUES (?,?,?,?,?,?,?)";
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1,foli);
            pst.setString(2,nom);
            pst.setString(3,apat);
            pst.setString(4,amat);
            pst.setString(5,((JTextField)FechaP.getDateEditor().getUiComponent()).getText());
            pst.setString(6,sex);
            pst.setString(7,cl);
            int n=pst.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(null,"Registro guardado con exito");
                limpiar();
                bloquear();
            }
        } catch (SQLException ex) {
            //Logger.getLogger(vInicio.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Folio ya registrado");
        }
        }
    }//GEN-LAST:event_btnGuardarPActionPerformed

    private void btnEditarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPActionPerformed
        conexion cc=new conexion();
        Connection cn = cc.conexion();
        Statement st;
        PreparedStatement ps;
        ResultSet rs;
        String fol,sex = null;
        if(femenino.isSelected()){
            sex="F";
        } else if (masculino.isSelected())
            sex="M";
        fol = tfFolioP.getText();
        String sql = "UPDATE PACIENTE SET nombre = '"+tfNombreP.getText()+"',apellidoPat = '"+tfApellidoPatP.getText()+"',apellidoMat = '"+tfApellidoMatP.getText()+"',sexo = '"+sex+"' WHERE folio_p = '"+tfFolioP.getText()+"'";
        if (tfFolioP.getText().length()==0 || tfNombreP.getText().length()==0 || tfApellidoPatP.getText().length()==0 || tfApellidoMatP.getText().length()==0 || FKdTablaPaciente.getText().length()==0){
            JOptionPane.showMessageDialog(null,"ERROR CAMPOS VACIOS");
        }
        else{
            try {
                PreparedStatement pst = cn.prepareStatement(sql);
                int res = pst.executeUpdate();
                if(res >0 ){
                    JOptionPane.showMessageDialog(null, "Datos modificados");
                    tfNombreP.setText(null);
                    tfApellidoPatP.setText(null);
                    tfApellidoMatP.setText(null);
                    buttonGroup1.clearSelection();
                    limpiar();
                    }
                else{
                    JOptionPane.showMessageDialog(null, "Error al modificar los datos");
                }
            } catch (Exception e) {
                     JOptionPane.showMessageDialog(null, String.valueOf(("Error: " + e)));
            }
        }
    }//GEN-LAST:event_btnEditarPActionPerformed

    private void btnBorrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPActionPerformed
        conexion cc=new conexion();
        Connection cn = cc.conexion();
        String fol;
        fol = tfFolioP.getText();
        NuevoP.setEnabled(true);
        btnGuardarP.setEnabled(false);
        if (tfFolioP.getText().length()==0 || tfNombreP.getText().length()==0 || tfApellidoPatP.getText().length()==0 || tfApellidoMatP.getText().length()==0 || FKdTablaPaciente.getText().length()==0){
            JOptionPane.showMessageDialog(null,"ERROR CAMPOS VACIOS");
        }
        else{
            if(tfFolioP.getText().length()>0){
                int r =JOptionPane.showConfirmDialog(null, "¿Seguro de que quiere eliminar los datos?");
                if(r==0){
                    try {
                        PreparedStatement pps = cn.prepareStatement("DELETE FROM paciente WHERE folio_p='"+fol+"'");
                        pps.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Datos eliminados correctamente");
                        limpiar();
                    } catch (SQLException ex) {
                        Logger.getLogger(vInicio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                }
            }
        }
    }//GEN-LAST:event_btnBorrarPActionPerformed

    private void btntutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntutorActionPerformed
    conexion cc=new conexion();
    Connection cn = cc.conexion();
    String [] columnas={"Clave_t","Nombre","Apellido Paterno","Apellido Materno"};
    String [] registro=new String[4];
    ModeloTabla=new DefaultTableModel(null,columnas);      
    String SSQL;
    String cla;
    cla = FKdTablaPaciente.getText();
        SSQL= "SELECT * FROM tutor WHERE clave_t='"+cla+"'";
        try {
            PreparedStatement st = cn.prepareStatement(SSQL);
            ResultSet rs = st.executeQuery();

        while (rs.next()){
            registro[0]=rs.getString("clave_t");
            registro[1]=rs.getString("nombre");
            registro[2]=rs.getString("apellidoPat");
            registro[3]=rs.getString("apellidoMat");
          
            ModeloTabla.addRow(registro);
           
        }
        tbDatos.setModel(ModeloTabla);
    } catch (SQLException e) {
      //JOptionPane.showMessageDialog(null, e, "Error durante el procedimiento", JOptionPane.ERROR_MESSAGE);      
      JOptionPane.showMessageDialog(null, "ERROR");
    }
    }//GEN-LAST:event_btntutorActionPerformed

    private void btnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPActionPerformed
        conexion cc=new conexion();
        Connection cn = cc.conexion();
        lares.setVisible(true);
        fecha1.setVisible(true);
        String sql="";
        sql="SELECT * FROM paciente WHERE folio_p=?";
        try{
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1,tfFolioP.getText());
            rs=pst.executeQuery();
            
            if(rs.next()){
                tfNombreP.setText(rs.getString("nombre"));
                tfApellidoPatP.setText(rs.getString("apellidoPat"));
                tfApellidoMatP.setText(rs.getString("apellidoMat"));
                String w = rs.getString("sexo");
                lares.setText(rs.getString("sexo"));
                if ( w.equalsIgnoreCase("F")){
                    femenino.setSelected(true);
                }else{ if(w.equalsIgnoreCase("M")){
                    masculino.setSelected(true);}
                    else{
                        System.out.println("Error");
                        }}
                fecha1.setText(rs.getString("fecha_nac"));
                FKdTablaPaciente.setText(rs.getString("clave_t"));
            }
            
        }catch (SQLException e) {
                //JOptionPane.showMessageDialog(null, String.valueOf(("Error: " + e)));
                JOptionPane.showMessageDialog(null, "ERROR");
        }
    }//GEN-LAST:event_btnBuscarPActionPerformed

    private void tfFolioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFolioPActionPerformed
        tfFolioP.transferFocus();
    }//GEN-LAST:event_tfFolioPActionPerformed

    private void tfNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombrePActionPerformed
        tfNombreP.transferFocus();
    }//GEN-LAST:event_tfNombrePActionPerformed

    private void tfApellidoPatPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoPatPActionPerformed
        tfApellidoPatP.transferFocus();
    }//GEN-LAST:event_tfApellidoPatPActionPerformed

    private void tfApellidoMatPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoMatPActionPerformed
        tfApellidoMatP.transferFocus();
    }//GEN-LAST:event_tfApellidoMatPActionPerformed

    private void NuevoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoPActionPerformed
        desbloquear();
    }//GEN-LAST:event_NuevoPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FKdTablaPaciente;
    private com.toedter.calendar.JDateChooser FechaP;
    private javax.swing.JButton NuevoP;
    private javax.swing.JButton btnBorrarP;
    private javax.swing.JButton btnBuscarP;
    private javax.swing.JButton btnEditarP;
    private javax.swing.JButton btnGuardarP;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btntutor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fecha1;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lares;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTable tbDatos;
    private javax.swing.JTextField tfApellidoMatP;
    private javax.swing.JTextField tfApellidoPatP;
    private javax.swing.JTextField tfFolioP;
    private javax.swing.JTextField tfNombreP;
    // End of variables declaration//GEN-END:variables
}
